### ISSUE TITLE
Class-Handlers Support

### ISSUE THREAD

**Issue by antonio-gg-dev** [gacela-project/router#15]
Should we support handlers being classes as well as functions? This would allow developers to encapsulate error handling or even group them by modules.

Handlers would end up being similar to controllers.

Perhaps in a future iteration we could even allow dependency injection to them, also just like controllers 🤔.

**Comment by antonio-gg-dev** [comment]
In addition, in the PR #14 implementation I had to do a little workaround to be able to encapsulate the built-in handlers in classes 😅.

https://github.com/gacela-project/router/blob/fe43af1f3e387931e2a78de1736d25a80fb18097/src/Router/Handlers.php#L38-L48

**Comment by Chemaclass** [comment]
I got an idea how to do this. I will create a PR soonish 🏃🏼

**Comment by Chemaclass** [comment]
Implemented here: https://github.com/gacela-project/router/pull/16
